title: "SOFIE GSoC '26 Logbook"
description: "Engineering logbook for SOFIE parallel kernel development in GSoC 2026"
url: "https://mmadan128.github.io"
baseurl: "/SOFIE-GSoC-26"
repository: "mmadan128/SOFIE-GSoC-26"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

mathjax: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false

author:
  name: "Mohit Madan"
  bio: "GSoC 2026 Contributor for CERN-HSF. B.Tech CST @ MAIT."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmadan128"
