title: "Logbook"
description: "ML Inference on heterogeneous architectures using SOFIE"
url: "https://mmadan128.github.io"
baseurl: "/SOFIE-GSoC-26"
repository: "mmadan128/SOFIE-GSoC-26"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

mathjax: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs"
      toc: true
      toc_sticky: true
      toc_label: "On this page"
      read_time: true
      share: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs"
      toc: true
      toc_sticky: true
      toc_label: "On this page"

author:
  name: "Mohit Madan"
